apiVersion: apps/v1
kind: Deployment
metadata:
  name: bananas-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bananas-service
  template:
    metadata:
      labels:
        app: bananas-service
    spec:
      containers:
        - name: bananas-service
          image: bananas-service:latest
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
