apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml

namespace: apps

images:
  - name: bananas-service
    newName: bananas-service:latest
    newTag: 1.0.0
