name: CICD

on:
  push:
    branches:
      - main

env:
  SERVICE_NAME: bananas-service
  APP_MANIFESTS_REPO: rw-gitops-demo/app-manifests
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TAG_NAME: 1.0.${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create tag
        run: |
          git tag ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}

      - name: Create release
        uses: ./.github/templates/create-release
        if: ${{ github.run_number != 1 }}
        with:
          token: ${{ github.token }}
          tag-name: ${{ env.TAG_NAME }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  deploy-to-dev:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy
        uses: ./.github/templates/deploy
        with:
          env: dev
          aws-account-id: 111111111111
          aws-region: eu-west-1
          kubeconfig: ${{ secrets.DEV_KUBECONFIG }}
          registry: ${{ env.REGISTRY }}
          image-name: ${{ env.IMAGE_NAME }}
          tag-name: ${{ env.TAG_NAME }}

  deploy-to-prod:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
      contents: read
    needs: deploy-to-dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy
        uses: ./.github/templates/deploy
        with:
          env: prod
          aws-account-id: 222222222222
          aws-region: eu-west-1
          kubeconfig: ${{ secrets.PROD_KUBECONFIG }}
          registry: ${{ env.REGISTRY }}
          image-name: ${{ env.IMAGE_NAME }}
          tag-name: ${{ env.TAG_NAME }}
